### ISSUE TITLE
playlist_create() returns false - But Playlist is indeed created on server

### ISSUE THREAD

**Issue by DjTuxeedo** [lachlan-00/python3-ampache#2]
When I run the Example code:

playlist_create = (ampache.playlist_create(ampache_url, ampache_api, 'python-test', 'private'))

returns playlist_create == false

but on the server the playlist "python-test" has been created.
in the doc it says: 

""" playlist_create
    MINIMUM_API_VERSION=380001
    This create a new playlist and return it
    INPUTS
    * ampache_url = (string)
    * ampache_api = (string)
    * name        = (string)
    * type        = (string)
"""

**Comment by DjTuxeedo** [comment]
It Turns out, Ampache somehow does not really support empty playlists.
Empty Playlists are not displayed through xml-api however they can be created through xml-api
ironically the are displayed through subsonic api where they cannot be created.

From what I understand it's impossible to create a new playlist via Python-Ampache and get a reference to further fill it with songs. I can create an empty playlist for which the handle is not returned and it doesn't appear in any playlist search method. Somehow this new list gets lost in Translation (in the Browser GUI it is displayed though).

Can anyone help in this regard?

**Comment by DjTuxeedo** [comment]
I see ampache 4.0.4 was released only 16 Days ago and there have been changes in the xml-api Playlist handling. there might be a bug hidden there :-)

**Comment by lachlan-00** [comment]
There is and I've fixed that in develop.

The API has only ever returned playlists with items. I'll be making a new release soon to cover that

**Comment by lachlan-00** [comment]
(Ampache develop)

**Comment by DjTuxeedo** [comment]
wow great, 
fyi: I also filed an issue at the Ampache github page
did you change the Ampache xml response to get the expected outcome? My xml response to "playlist_create" looks like this:

<?xml version="1.0" encoding="UTF-8" ?>
<root>
<total_count>1</total_count>
</root>

I'll update the server to develop branch to test. Thanks a lot for the quick response

**Comment by lachlan-00** [comment]
Don't worry about updating to develop. I want to release 4.1.0 today after testing the changes in other areas but I'll also make sure the actual responses are good too

Please keep trying things out though we are starting to get a good group of users for the API together who have been really helpful! :)

**Comment by DjTuxeedo** [comment]
Would it help if I downgrade to 4.0.3 ?

**Comment by lachlan-00** [comment]
not really, i'm almost done with 4.1.0-develop just have had christmas things this week to deal with.

**Comment by DjTuxeedo** [comment]
Sry to nag on you. Spending time with your loved ones and enjoying the holiday season is indeed more important. Merry Christmas :-)

**Comment by lachlan-00** [comment]
4.1.0 is out now with an api that doesn't discriminate the size of the playlist

**Comment by DjTuxeedo** [comment]
Hey ho, Happy new Year.
Maybe the same or maybe an new Issue?
With 4.1.0 on my server I try to execute the following code (Taken from Playlist.py):

playlist_create = (ampache.playlist_create(ampache_url, ampache_api, 'python-test', 'private'))
if playlist_create:
    for child in playlist_create:
        if child.tag == 'playlist':
            single_playlist = child.attrib['id']
print('\nplaylist_create created the following id:\n    ', single_playlist)

songs = ampache.get_indexes(ampache_url, ampache_api, 'song', '', '', '', '', 10)
for child in songs:
    if child.tag == 'song':
        print(ampache.playlist_add_song(ampache_url, ampache_api, single_playlist, child.attrib['id'], 1))
        print(ampache.playlist_add_song(ampache_url, ampache_api, single_playlist, child.attrib['id'], 1))

I get the following error:
playlist_add_song() takes 4 positional arguments but 5 were given

If I delete the fifth argument i get the following error:
Access to this Playlist is denied (Translation)

Is there a setting I need to update before I can add songs to a newly created playlist?
Thank you very much for your help :-)

**Comment by DjTuxeedo** [comment]
Ah, if I give my user admin privileges i get the message, that the song is added to the playlist. But in the UI I still see no songs in the playlist no matter how many songs I try to add :-(

**Comment by lachlan-00** [comment]
I'll see what's happening. i have generally only been using my example files for this so far so it'll be good to tet your code as well.

**Comment by lachlan-00** [comment]
I added check as an option and didn't update the src ampache.py with the change.

0/1 for check will skip duplicates.

**Comment by lachlan-00** [comment]
made a bugfix release 1.0.3

**Comment by DjTuxeedo** [comment]
You're a genius!
Works as expected.
ThanxALot
